server:
  port: 8801

zuul:
  routes:
    demo:
      path: /demo-filter
spring:
  application:
    name: gateway-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8802/eureka